### ISSUE TITLE
[Question] About Addons

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [Ifera/ScoreHud#162]
Since I am to dumb to understand stuff, did you remove addon support and replaced it where if you have the plugin, the tags work?

**Comment by Ifera** [comment]
Addons were a bad implemention and an easy way out of a problem which I didn't want to deal at that point in time. These are jow completely removed. 

As you might have read already, ScoreHud now is event driven i.e. instead of updated every 20 or so ticks, it updates only when there is an update which greaty improves performance.

Please refer to the ScoreHud wiki if you want to see how tags work and how you can make tags for your own plugin. 
Furthermore, its on to the plugin developers now to supply tags for ScoreHud and not the other way around. If you want ScoreHud to support a plugin then add the owner of that plugin to either add ScoreHud in their own plugin or supply you with a plugin which adds those tags. 
Also there you can head over to [ScoreHudX](https://github.com/Ifera/ScoreHudX) repo for some pre-built plugins supplying you with the tags.
